import sys
from queue import Empty as Empty, Full as Full
from typing import Any

if sys.version_info >= (3, 13):
    from queue import ShutDown as ShutDown

class Queue:
    maxsize: int

    def __init__(self, maxsize: int = 0) -> None: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    def put(
        self, item: Any, block: bool = True, timeout: float | None = None
    ) -> None: ...
    def put_nowait(self, item: Any) -> None: ...
    def get(self, block: bool = True, timeout: float | None = None) -> Any: ...
    def get_nowait(self) -> Any: ...
    def task_done(self) -> None: ...
    def join(self) -> None: ...
    if sys.version_info >= (3, 13):
        def shutdown(self, immediate: bool = False) -> None: ...
